[package]
name = "nextjs-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
swc_common = "0.31.0"
swc_ecma_parser = "0.137.0"
swc_ecma_ast = "0.107.0"
swc_ecma_visit = "0.93.0"
colored = "2.0.0"
